import { MockSale } from '@/components/garagehunt/sale-card';

export const MOCK_SALES: MockSale[] = [
  {
    id: '1',
    title: 'Maple Street moving sale',
    distanceKm: 1.2,
    latitude: 42.9849,
    longitude: -81.2453,
    startDate: '2026-07-05',
    endDate: '2026-07-05',
    dailyStartTime: '9am',
    dailyEndTime: '2pm',
    categories: ['Furniture', 'Tools'],
    tagLabel: 'Live now',
    tagVariant: 'live',
    icon: 'image-outline',
    addressLabel: 'Maple Street area, London',
    description: 'Moving sale, everything must go. Couch, dining set, power tools, and a dozen boxes of odds and ends.',
    favoriteCount: 14,
    eventId: null,
    otherItems: [],
    photos: [],
    sellerId: 'mock-seller-1',
    sellerRating: 4.8,
    sellerReviewCount: 23,
    checkinCount: 0,
    isBoosted: false,
  },
  {
    id: '2',
    title: 'Riverdale community sale',
    distanceKm: 1.8,
    latitude: 42.9905,
    longitude: -81.251,
    startDate: '2026-07-11',
    endDate: '2026-07-11',
    dailyStartTime: '9am',
    dailyEndTime: '1pm',
    categories: ['Furniture', 'Kids'],
    tagLabel: '42 homes',
    tagVariant: 'town',
    icon: 'people-outline',
    addressLabel: 'Riverdale neighbourhood, London',
    description: '42 homes across Riverdale are participating in this town-wide event. One map, one route, one Saturday morning.',
    favoriteCount: 24,
    eventId: 'mock-riverdale-event',
    otherItems: [],
    photos: [],
    sellerId: 'mock-seller-2',
    sellerRating: null,
    sellerReviewCount: 0,
    checkinCount: 0,
    isBoosted: false,
  },
  {
    id: '3',
    title: 'Oakwood family sale',
    distanceKm: 2.4,
    latitude: 42.978,
    longitude: -81.234,
    startDate: '2026-07-11',
    endDate: '2026-07-11',
    dailyStartTime: '10am',
    dailyEndTime: '3pm',
    categories: ['Kids', 'Clothing'],
    tagLabel: 'New',
    tagVariant: 'new',
    icon: 'image-outline',
    addressLabel: 'Oakwood Ave area, London',
    description: 'Kids clothing (0-8y), toys, a crib, and a stroller in great condition. Cash or e-transfer.',
    favoriteCount: 3,
    eventId: null,
    otherItems: [],
    photos: [],
    sellerId: 'mock-seller-3',
    sellerRating: null,
    sellerReviewCount: 0,
    checkinCount: 0,
    isBoosted: false,
  },
  {
    id: '4',
    title: 'Birchmount tool blowout',
    distanceKm: 3.4,
    latitude: 42.992,
    longitude: -81.22,
    startDate: '2026-07-11',
    endDate: '2026-07-11',
    dailyStartTime: '8am',
    dailyEndTime: '12pm',
    categories: ['Tools'],
    tagLabel: 'Scheduled',
    tagVariant: 'scheduled',
    icon: 'construct-outline',
    addressLabel: 'Birchmount Rd area, London',
    description: 'Downsizing the workshop — hand tools, a table saw, and assorted hardware bins.',
    favoriteCount: 5,
    eventId: null,
    otherItems: [],
    photos: [],
    sellerId: 'mock-seller-4',
    sellerRating: 5.0,
    sellerReviewCount: 2,
    checkinCount: 0,
    isBoosted: false,
  },
  {
    id: '5',
    title: 'Elmwood estate sale',
    distanceKm: 4.1,
    latitude: 42.97,
    longitude: -81.26,
    startDate: '2026-07-12',
    endDate: '2026-07-12',
    dailyStartTime: '9am',
    dailyEndTime: '4pm',
    categories: ['Antiques', 'Furniture'],
    tagLabel: 'Scheduled',
    tagVariant: 'scheduled',
    icon: 'image-outline',
    addressLabel: 'Elmwood area, London',
    description: 'Full estate sale — antique furniture, china, vintage decor, and collectibles.',
    favoriteCount: 8,
    eventId: null,
    otherItems: [],
    photos: [],
    sellerId: 'mock-seller-5',
    sellerRating: null,
    sellerReviewCount: 0,
    checkinCount: 0,
    isBoosted: false,
  },
  {
    id: '6',
    title: 'Willowdale multi-family sale',
    distanceKm: 5.0,
    latitude: 43.001,
    longitude: -81.265,
    startDate: '2026-07-11',
    endDate: '2026-07-12',
    dailyStartTime: '8am',
    dailyEndTime: '1pm',
    categories: ['Clothing', 'Books'],
    tagLabel: 'This weekend',
    tagVariant: 'category',
    icon: 'shirt-outline',
    addressLabel: 'Willowdale area, London',
    description: 'Three families, one driveway. Clothing for all ages, books, records, and kitchenware.',
    favoriteCount: 6,
    eventId: null,
    otherItems: ['Records'],
    photos: [],
    sellerId: 'mock-seller-6',
    sellerRating: 4.2,
    sellerReviewCount: 5,
    checkinCount: 0,
    isBoosted: false,
  },
];
